version: "3.1"

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:80
    volumes:
      - ./src:/var/www/html/
    env_file:
      - .env

  db:
    image: mysql:8.0.40
    environment:
      MYSQL_DATABASE: adsrocas
      MYSQL_USER: dev
      MYSQL_PASSWORD: 123
      MYSQL_ROOT_PASSWORD: 123
    ports:
      - "3036:3306"
    volumes:
      - ./db:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  phpmyadmin:
    image: phpmyadmin
    ports:
      - 8081:80
    environment:
      PMA_HOST: db
    volumes:
      - ./phpmyadmin_logs:/var/log/apache2

volumes:
  php:
  db:
  phpmyadmin_logs:
